package exnihiloadscensio.registries;

import java.util.ArrayList;

import org.apache.commons.lang3.StringUtils;

import exnihiloadscensio.ExNihiloAdscensio;
import exnihiloadscensio.items.ore.ItemOre;
import exnihiloadscensio.items.ore.Ore;
import exnihiloadscensio.texturing.Color;
import exnihiloadscensio.util.ItemInfo;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry;
import net.minecraftforge.fml.common.registry.GameRegistry;
import net.minecraftforge.fml.common.registry.RegistryBuilder;

public class OreRegistry {
	
	public static final int INVALID_ID = Short.MAX_VALUE - 1;
    public static FMLControlledNamespacedRegistry<Ore> ORES;
    
    private static ArrayList<Ore> registry = new ArrayList<Ore>();
    
    public static void registerDefaults() {
    	ORES = (FMLControlledNamespacedRegistry<Ore>) new RegistryBuilder<Ore>()
                .setName(new ResourceLocation(ExNihiloAdscensio.MODID, "ores"))
                .setIDRange(0, INVALID_ID - 1)
                .setType(Ore.class)
                .create(); 
    	
    	registerOre("gold", new Color("FFFF00"), new ItemInfo(Items.GOLD_INGOT, 0));
    	registerOre("iron", new Color("BF8040"), new ItemInfo(Items.IRON_INGOT, 0));
    }
    
    /**
     * Registers a new custom piece, hunk, dust and potentially ingot to be generated by Ex Nihilo Adscensio.
     * @param name Unique name for ore
     * @param color Color for the pieces
     * @param info Final result for the process. If null, an ingot is generated. Otherwise, the hunk will be
     * smelted into this.
     * @return Ore[], containing the piece, hunk and ingot if called for.
     */
    public static Ore[] registerOre(String name, Color color, ItemInfo info) {
    	Ore[] ret = new Ore[3];
    	
    	ret[0] = new Ore(name, color, info); registry.add(ret[1]);
    	ret[1] = new Ore("hunk"+StringUtils.capitalize(name), color, info);
    	ret[2] = new Ore("dust"+StringUtils.capitalize(name), color, info);
    	if (info == null)
    		ret[3] = new Ore("ingot"+StringUtils.capitalize(name), color, info);
    		
    	return ret;
    }
    
    public static void doRecipes() {
    	for (Ore ore : ORES.getValues()) {
    		if (ore.getRegistryName().toString().contains("hunk") ||
    				ore.getRegistryName().toString().contains("ingot") ||
    				ore.getRegistryName().toString().contains("dust"))
    			continue;
    		
    		String[] name = ore.getRegistryName().toString().split(":");
    		ItemStack in = ItemOre.getStack(ore);
    		
    		Ore resultOre = ORES.getValue(new ResourceLocation(name[0]+":hunk"+StringUtils.capitalize(name[1])));
    		ItemStack result = ItemOre.getStack(resultOre);
    		
    		GameRegistry.addShapedRecipe(result, new Object[] {"xx","xx", 'x', in});
    		
    		if (ore.getResult() == null) {
    			Ore smeltingResultOre = ORES.getValue(new ResourceLocation(name[0]+":ingot"+StringUtils.capitalize(name[1])));
    			ItemStack smeltingResult = ItemOre.getStack(smeltingResultOre);
    			GameRegistry.addSmelting(result, smeltingResult, 0.7f);
    		}
    		else {
    			ItemStack smeltingResult = ore.getResult().getItemStack();
    			GameRegistry.addSmelting(result, smeltingResult, 0.7f);
    		}
    	}
    }

}
